# Generated by Buildr 1.4.6, change to your liking

# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "unima_lski"
COPYRIGHT = ""



# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"
repositories.remote << "http://elk-reasoner.googlecode.com/svn-history/r293/m2/releases"

desc "The Gold-miner project"
define "gold-miner" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  eclipse_layout = Layout.new
  eclipse_layout[:source, :main, :java] = 'src'
  eclipse_layout[:source, :main, :resources] = 'res'

  define "GoldMiner", :layout=>eclipse_layout do
    package(:jar).with(:manifest => _('src/META-INF/MANIFEST.MF')).merge(Dir[_("dependencies/*.jar")])
    compile.with Dir[_("dependencies/*.jar")]
  end

end
