# Generated by Buildr 1.4.6, change to your liking

# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "unima_lski"
COPYRIGHT = ""



# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"
repositories.remote << "http://elk-reasoner.googlecode.com/svn-history/r293/m2/releases"

desc "The Gold-miner project"
define "gold-miner" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  eclipse_layout = Layout.new
  eclipse_layout[:source, :main, :java] = 'src'
  eclipse_layout[:source, :main, :resources] = 'res'

  PELLET='com.owldl:pellet:jar:2.3.0'
  download artifact(PELLET) => 'file:///home/daniel/Repositories/gold-miner/GoldMiner/dependencies/pellet-core.jar'
  ATERM='com.owldl:aterm:jar:1.6.0'
  download artifact(ATERM) => 'file:///home/daniel/Repositories/gold-miner/GoldMiner/dependencies/aterm-java-1.6.jar'
  PELLETOWLAPI3='com.owldl:pellet-owlapiv3:jar:2.3.0'
  download artifact(PELLETOWLAPI3) => 'file:///home/daniel/Repositories/gold-miner/GoldMiner/dependencies/pellet-owlapiv3.jar'

  define "GoldMiner", :layout=>eclipse_layout do
    package = :jar
    compile.with PELLET, PELLETOWLAPI3, ATERM
    compile.with transitive('com.hp.hpl.jena:jena:jar:2.6.4')
    compile.with transitive('com.hp.hpl.jena:arq:jar:2.8.8')
    compile.with transitive('net.sourceforge.owlapi:owlapi-all:jar:3.2.4')
    compile.with transitive('junit:junit:jar:4.8.2')
    compile.with transitive('mysql:mysql-connector-java:jar:5.1.6')
  end

end
