package miner.util;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Collection;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;

/**
 * Utility class for normalizing the confidence values generated by different mining methods. This enables us to have
 * one common confidence threshold instead of one per method.
 */
public class ScalingValueNormalizer implements ValueNormalizer {

    private final static Logger log = LoggerFactory.getLogger(ScalingValueNormalizer.class);
    private static int normalizerCount = 0;
    private String name;
    private double minValue = Double.MAX_VALUE;
    private double maxValue = Double.MIN_VALUE;

    /**
     * Initializes the normalization system with the given name. The name is mostly used to uniquely identify the
     * normalizer in log messages.
     *
     * @param name name identifying this normalizer uniquely
     */
    public ScalingValueNormalizer(String name) {
        log.info("initializing with name '{}'", name);
        this.name = name;
    }

    /**
     * Initializes the normalization system using an automatically generated name.
     */
    public ScalingValueNormalizer() {
        this("confidence-normalizer-" + normalizerCount);
        normalizerCount++;
    }

    /**
     * Reports the value of the given target to the normalizer so that it can be took into consideration for the
     * normalization phase
     *
     * @param target target whose value to report
     */
    @Override
    public void reportValue(NormalizationTarget target) {
        log.debug("({}) Got value '{}' reported", name, target);
        double value = target.getValue();
        if (value > maxValue) {
            log.debug("({}) Applied '{}' as new max value, previous was '{}'", new Object[]{name, value, maxValue});
            maxValue = value;
        }

        if (value < minValue) {
            log.debug("({}) Applied '{}' as new min value, previous was '{}", new Object[]{name, value, minValue});
            minValue = value;
        }
    }

    /**
     * Reports the values of all normalization targets contained in the given collection to the normalizer.
     *
     * @param targets collection of targets whose values to report
     */
    @Override
    public void reportValues(Collection<? extends NormalizationTarget> targets) {
        log.debug("({}) Reporting {} values to normalizer", name, targets.size());
        for (NormalizationTarget target : targets) {
            reportValue(target);
        }
        log.debug("({}) Done reporting values", name);
    }

    /**
     * Normalizes the values contained in the given target. This method directly modifies the single objects in the
     * given collection. Take this into account when your collection is sensitive to such changes!
     *
     * @param collection collection of targets to normalize
     *
     */
    @Override
    public void normalize(Collection<? extends NormalizationTarget> collection) {
        log.info("({}) Starting normalization for collection containing {} elements", name, collection.size());
        log.info("({}) Max value: {}", name, maxValue);
        log.info("({}) Min value: {}", name, minValue);

        for (NormalizationTarget target : collection) {
            double scaledValue = scale(target.getValue());
            target.setValue(scaledValue);
        }
        log.debug("({}) Done normalization");
    }

    /**
     * Scales the given value according to the values this normalizer got reported.
     *
     * @param value value to scale
     * @return scaled value
     */
    private double scale(double value) {
        return (value - minValue) / (maxValue - minValue);
    }


    public static void main(String[] args) {
        ValueNormalizer vn = new ScalingValueNormalizer("testnormalizer");
        Set<NormalizationTarget> targets = new HashSet<NormalizationTarget>();
        Random rand = new Random();
        for (int i = 0; i < 20; i++) {
            targets.add(new DummyNormalizationTarget(rand.nextDouble()*100));
        }

        vn.reportValues(targets);
        vn.normalize(targets);

        for (NormalizationTarget t : targets) {
            System.out.println(t);
        }
    }
}
